sudo: true
#language: php
#php:
#- '7.1'

script:
  - ARTIFACT_NAME=${TRAVIS_COMMIT_RANGE:0:6}; export ARTIFACT_NAME;
  - if [[ $TRAVIS_PULL_REQUEST -ne 'false' ]]; then ./scripts/pr-pipeline.sh ; fi
  - if [[ $TRAVIS_PULL_REQUEST == 'false' && $TRAVIS_BRANCH = "master" ]]; then ./scripts/merge-pipeline.sh ; fi
